export interface CoreValue {
  number: number;
  title: string;
  slug: string;
  excerpt: string;
  imageUrl?: string;
  body: string[]; // each string is a paragraph
}

export const CORE_VALUES: CoreValue[] = [
  {
    number: 1,
    title: "Acknowledge, Obey, and Be Grateful",
    slug: "acknowledge-obey-grateful",
    excerpt:
      "It is the duty of all nations to acknowledge, obey, and be grateful to almighty God—the source of all order and blessing.",
    imageUrl: "/images/Washington-Night-Ops.png",
    body: [
      "\"It is the duty of all nations to acknowledge, obey, and be grateful to Almighty God.\"",
      "George Washington, a figure of unparalleled respect and admiration, left an indelible mark with his leadership, vision, and steadfast principles. As the inaugural President of the United States and a pivotal figure in the nation's birth, his words and deeds continue to shape our country's ethos. His quote, a testament to his personal beliefs, echoes a guiding principle that resonates deeply within our Honor Bound tribe.",
      "I said the quote resonates with OUR tribe. Unfortunately, it doesn't resonate with all Americans. Harrison Butker recently expressed Christian views while giving a graduation speech at a Christian college, inciting outrage from non-Christian listeners, proving that acknowledging, obeying, and being grateful to God isn't always easy, encouraged, or even tolerated.",
      "Actions (and choices) have consequences. At Honor Bound FIT, we choose to live and proclaim our values loudly. We literally wear them on our backs. First and chief among them is our belief in, and obedience to, Almighty God.",
      "America is often described as a tapestry woven with various cultures, beliefs, and backgrounds. While the necessary separation of church and state remains a cornerstone of the American Constitution, the acknowledgment of a shared moral compass can play a significant role in fostering a sense of commonality and dignity among Americans. This shared understanding has certainly fostered a sense of unity within the Honor Bound tribe.",
      "Obedience to a higher moral standard is crucial for business leadership and ethical governance. Trust in our institutions has been shaken by scandals and partisan conflicts. We could restore faith in leadership by adhering to moral and ethical guidelines. Washington's call to obey a higher authority underscores the importance of integrity, accountability, and transparency. Leaders who prioritize these values inspire confidence and foster trust, ensuring that their actions serve the best interests of those in their charge.",
      "Gratitude, whether it be to God, or in any area of your life, is transformative. Dennis Prager says: \"All happy people are grateful. Ungrateful people cannot be happy. We tend to think that being unhappy leads people to complain, but it's truer to say that complaining leads to people becoming unhappy.\" Feeling and expressing gratitude for our freedoms, opportunities, and blessings fosters a more positive and cohesive society. This sense of appreciation inspires acts of kindness, community service, and a willingness to support those in need.",
      "When Keith and I first discussed my intent to cultivate a too-long list of Core Values for Honor Bound FIT, to shape and inform the decisions we make and the culture we create within our organization, I told him I intend to write at least one article for every value. When asked where I would find the time and inspiration for that much writing, I said: \"I have no idea where I'll find the time, but between the Disciples, the Stoics, and the Founding Fathers, I'm fairly certain I'll have plenty of inspiration.\" As we anticipate facing unknowable challenges, Washington's timeless wisdom provides the first step in guiding us toward a brighter future.",
    ],
  },
  {
    number: 2,
    title: "The Greatest Political Document Ever Written",
    slug: "greatest-political-document",
    excerpt:
      "The United States Constitution stands alone as the greatest political document ever conceived—a covenant of ordered liberty.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2025/06/Honor-Bound-FIT-US-Constitution.png",
    body: [
      "The United States Constitution isn't just a set of rules — it's a transformational document. It's a moral and political blueprint for freedom and order. This isn't exaggeration. It's truth — bold and sometimes inconvenient, but truth all the same.",
      "The Constitution reflects the Declaration of Independence: all men are created equal and have rights from their Creator — not government. These rights are universal and unchangeable. Dennis Prager says liberty without virtue is chaos; virtue without liberty is tyranny. The Constitution protects against both. It's built on human nature, not utopian ideals. Like strength training, it works through discipline and limits — not flash, but foundation. It's the deadlift of democracy: heavy, essential, and strengthening.",
      "Jordan Peterson often talks about the need for structure. The Constitution's authors understood this long ago. They knew power corrupts, so they built checks and balances — like a squat rack for society. The Constitution doesn't expect perfection. It provides structure so we can grow stronger, not weaker, under pressure.",
      "Charlie Kirk reminds us — America's greatness isn't luck. It's rooted in the Constitution. This document unleashed freedom, prosperity, and civil rights. No country has done more to defend liberty and lift people out of poverty — not despite the Constitution, but because of it. It's America's training manual — built on grit, not comfort. That's why people fight to come here. Why the flag inspires. Why tyrants fear it.",
      "Today, the Constitution is threatened — not by enemies abroad, but by those who misunderstand or resent it. Some call it a \"living document,\" meaning it says whatever they want. But if it can mean anything, it means nothing. Ignoring the Constitution is like skipping form in the gym — it leads to weakness. Discipline is required.",
      "In a world ruled by emotion and relativism, the Constitution stands firm. It protects your right to feel differently. It shields you from the mob. It doesn't guarantee happiness — just the freedom to pursue it. It ensures free speech, peaceful transitions of power, and individual liberty. It scares tyrants and inspires the oppressed. Like an elite fighting force, a free nation survives on structure. The Constitution is our battle-tested guide — built for endurance, not ease.",
      "Reagan said: \"Freedom is never more than one generation away from extinction.\" The Constitution isn't self-executing. It needs citizens of courage and conviction. So train your mind like your body — with discipline. Build the strength to carry its legacy forward. Defend it like you would your family and your freedom. The Constitution is the soul of the American experiment. And like anything worth fighting for, it must be earned — daily.",
    ],
  },
  {
    number: 3,
    title: "A Man's Most Sacred Duty Is to Protect Women and Children",
    slug: "mans-most-sacred-duty",
    excerpt:
      "There is no higher calling for a man than to protect those who cannot protect themselves. Strength means nothing if not wielded in defense of others.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2025/07/OKC-Firefighter-with-child.jpg",
    body: [
      "There is no higher calling for a man than to protect those who cannot protect themselves. At Honor Bound FIT, we believe this truth is written on the soul of every warrior. Strength, skill, and discipline mean nothing if they are not wielded in defense of others — most especially in defense of women and children.",
      "This is not some outdated relic of chivalry. It's an eternal principle — as real today as it was on the beaches of Normandy or the plains of ancient Sparta. This is not to suggest that women are weak or incapable. On the contrary — history is full of courageous mothers, first responders, and female warriors who have protected and sacrificed with unimaginable strength. But the fact that women can protect does not excuse men from the duty to do so. Our world needs more men who are willing to stand up, step in, and shoulder that sacred responsibility — not fewer.",
      "Jocko Willink says, \"Discipline equals freedom.\" And it is through this lens that we understand the sacred duty of protection. A man must first own himself — his body, mind, emotions, and actions — if he ever hopes to shoulder the burden of others. No one is coming to save you. You are the one who must be strong enough to stand between danger and the people you love. In the chaos of modern culture, it has become fashionable to confuse strength with oppression and masculinity with toxicity. Jordan Peterson flips that script: \"A harmless man is not a good man. A good man is a very dangerous man who has it under voluntary control.\" Protection requires potential for violence — and the wisdom to control it.",
      "At Honor Bound FIT, we don't train men to look good in the mirror. We train them to be ready when the moment comes. To run into danger. To lift heavier, ruck further, fight harder, endure longer — not for ego, but for duty. Ryan Michler of Order of Man calls this the \"Protector, Provider, Presider\" model. In his words: \"Masculinity isn't toxic. The lack of it is.\" The man who knows how to defend his wife, raise his children in strength and truth, and lead his community by example — that's the man we aim to forge.",
      "But it doesn't happen by accident. It takes resistance. It takes routine. It takes grit. Every squat, every sprint, every cold shower, every sacrifice of comfort — these are rehearsals for the real fight. Because when evil comes — and it will — the man who has trained himself in peace is the man who will rise in chaos. As Jordan Peterson often says, \"You should be a monster, and then you should learn how to control it.\" Controlled strength is what gives a man moral authority. Not to dominate — but to defend.",
      "Teddy Roosevelt, the original Rough Rider, believed that weakness — physical, moral, or political — was a curse. He called for men to embrace \"the strenuous life,\" to meet life's trials with grit and gusto, and to see strength not as selfish gain, but as a tool for service. He wrote: \"The first duty of a man is to be a good husband and father.\" That is not a passive role. It is active, sacrificial, and demanding. It is the battlefield of the everyday. Roosevelt didn't separate strength from virtue. To him, \"To educate a man in mind and not in morals is to educate a menace to society.\"",
      "Pastor Voddie Baucham puts it this way: \"If I teach my son to keep his eye on the ball, but not his eye on the cross, I have failed as a father.\" The protector role is not just about brute force. It is about character, conviction, and sacrifice. And let us say this plainly: women are capable of courage, protection, and leadership. We honor the mothers, police officers, firefighters, Marines, sailors, and warriors who put their lives on the line every day. But this truth remains — the failure of men to embrace their protective role has never made the world safer. It's made it more dangerous. Your sacred charge as a man is not only to lift heavy and fight hard — but to walk upright, speak truth, and lead your household with unshakable integrity. Because ultimately, the greatest threat to women and children is not the presence of strong men — it's the absence of them. To be a man is to stand guard.",
    ],
  },
  {
    number: 4,
    title: "The Obstacle Is the Way. Growth Is Found in Suffering.",
    slug: "the-obstacle-is-the-way",
    excerpt:
      "Every warrior knows that comfort never forged a fighter. The obstacle is not the end of the path — the obstacle is the path.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2025/08/ChatGPT-Image-Aug-26-2025-05_31_45-PM.avif",
    body: [
      "Every warrior knows that comfort never forged a fighter. Iron is sharpened on stone, and the human soul is refined in the crucible of hardship. At Honor Bound FIT, we don't run from obstacles — we run toward them. Because the obstacle is not the end of the path. The obstacle is the path.",
      "Few men have lived this truth as powerfully as Admiral James Stockdale. Shot down over North Vietnam in 1965, he spent nearly eight years as a prisoner of war in the infamous \"Hanoi Hilton.\" There, he endured torture, starvation, and years of solitary confinement. His body was broken, but his spirit never surrendered. Stockdale anchored himself in Stoic philosophy, especially the teachings of Epictetus and Seneca. Out of his endurance came what we now call the Stockdale Paradox — the discipline of holding two hard truths in tension: first, you must face the brutal facts of your present reality; second, you must never lose faith that you will prevail in the end. Many of his fellow prisoners clung to false optimism, telling themselves \"We'll be out by Christmas.\" When Christmas came and went, they broke. Stockdale refused such illusions. That paradox was the lifeline that carried him and others through hell itself.",
      "Centuries before Stockdale, the Roman Stoic philosopher Seneca wrote words that cut just as sharply today: \"Difficulties strengthen the mind, as labor does the body.\" He taught that prosperity breeds softness, while adversity sharpens character. Without suffering, there can be no courage, no perseverance, no wisdom. Every hardship is a forge, every trial a whetstone. To reject suffering is to reject growth. To embrace it is to discover the depth of your own resilience. At Honor Bound FIT, we take Seneca's wisdom into the gym and into life: the barbell that won't budge, the run that makes your lungs burn, the ruck that feels endless — all of it is the training ground for something greater than muscle. It is the training ground of the soul.",
      "The Stoics spoke of it. Admiral Stockdale embodied it. And today, warriors like Jocko Willink and David Goggins put it into words that ignite a fire in the modern age. For Jocko, the mantra is simple: \"Good.\" Bad situation? Good — it's a chance to adapt. Failed lift? Good — you've identified your weakness. Setback in life? Good — you now have an opportunity to grow. His disciplined frame strips away excuses and reveals the truth: obstacles are opportunities. If Jocko gives us the disciplined lens, David Goggins gives us the relentless edge. Goggins sees suffering not as a burden but as the ultimate teacher. Together, these voices echo the same ancient truth: growth is not found in comfort. It is found in suffering.",
      "Modern life has made it all too easy to avoid struggle. We drive instead of walk, eat instead of fast, scroll instead of sit in silence. In his book The Comfort Crisis, Michael Easter argues that this abundance of ease is quietly making us weak, sick, and restless. By insulating ourselves from discomfort, we've also insulated ourselves from growth. Easter suggests that humans are designed to push against challenge — to ruck long distances, to endure the elements, to wrestle with hunger and fatigue. His thesis echoes what the Stoics, warriors, and faith traditions have long said: comfort never made anyone strong.",
      "One of the greatest disservices a parent can do to a child is to clear every stone from their path. With good intentions, mothers and fathers often rush to shield their sons and daughters from hardship, disappointment, or struggle. But in sparing them suffering, they also spare them growth. A child who never faces failure, never hears the sting of \"no,\" or never learns the weight of responsibility, enters adulthood untested, untempered, and unprepared. As Seneca would remind us, difficulties are the very tools by which character is forged. To raise resilient men and women, we must allow them to encounter obstacles, to struggle against them, and to rise stronger on the other side.",
      "Even beyond philosophy and the warrior's ethos, the Christian tradition recognizes the refining fire of suffering. C.S. Lewis once wrote that \"pain is God's megaphone to rouse a deaf world.\" The Apostle Paul said it this way: \"Suffering produces endurance, endurance produces character, and character produces hope.\" (Romans 5:3-4). What the Stoics knew by reason, Paul confirmed by revelation: suffering is not the end. It is the pathway to transformation. The obstacle is not your enemy. It's your teacher, your forge, your proving ground. The obstacle is the way. Growth is found in suffering. And that is why we train.",
    ],
  },
  {
    number: 5,
    title: "Children Belong to Their Parents",
    slug: "children-belong-to-parents",
    excerpt:
      "The family is the first and most sacred institution of human society. Children belong to their parents — not to the state, not to the school, not to the culture.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2025/09/father-and-daughter-using-pull-up-bar-in-gym-2025-04-04-11-24-49-utc-scaled.avif",
    body: [
      "In every society, there are lines that must not be crossed. One of the most sacred is the line between parents and their children. A mother and father bring a child into the world; they nurture, guide, discipline, and raise that child into adulthood. That bond is natural, pre-political, and ancient. In the 1990s, Hillary Clinton popularized the phrase \"It takes a village to raise a child.\" The idea resonated with many because it highlighted the role of extended family and community support. But over time, that phrase has been stretched beyond its original intent. For some, it has become a justification for schools, governments, and cultural institutions to insert themselves into the sacred bond between parent and child. We reject that overreach. At Honor Bound FIT, we hold firmly to the truth: Children belong to their parents — not to the state, not to the school, not to the culture.",
      "Long before modern governments and public institutions, there was the family. Aristotle, writing in Politics, described the household as the most fundamental unit of society. Families exist by nature, he argued, and the authority of parents over children is rooted in the very structure of human life. For Aristotle, a healthy society depends on healthy families. The city-state is not primary — it is built from households. Undermine the household, and the entire society collapses. In our time, that warning remains relevant. When schools or governments encroach upon parental rights, they are not just making a policy mistake. They are sawing at the very branch society sits on. The family is not an accessory to civilization. It is the foundation.",
      "Nearly 2,000 years after Aristotle, Alexis de Tocqueville traveled to the United States to study its democratic experiment. In Democracy in America, he observed that the strength of American society lay in its families and local institutions. He was struck by how parents, communities, and churches — not distant governments — were the ones shaping the next generation. But Tocqueville also warned about a danger he called \"soft despotism\" — a future where the government, under the guise of helping, would begin to take over more and more responsibilities. Citizens, relieved of burdens, would slowly surrender their freedoms. When we see debates today over who has the final say in a child's education, medical care, or moral upbringing, Tocqueville's warning echoes loudly.",
      "Modern parents face immense pressure to outsource. Schools, coaches, social media platforms, and cultural institutions all present themselves as co-parents — or sometimes as replacements. But Jordan Peterson pushes back hard on that idea. Peterson insists that parents are responsible for who their children become. Responsibility cannot be delegated without consequence. A parent who fails to discipline, guide, and model virtue does not leave a neutral void — someone else will step in to fill it. And that \"someone else\" may not share the parent's values or love for the child. \"Do not let your children do anything that makes you dislike them,\" Peterson often says. It's a reminder that children must be formed intentionally.",
      "For many families, the question of parental authority is not just philosophical but deeply spiritual. Pastor and theologian Voddie Baucham is one of the clearest modern voices on this issue. Drawing from Scripture, he emphasizes that God entrusts children to parents — not to governments, schools, or cultural elites. Baucham is blunt about the dangers of neglecting that trust: \"If you give your children to Caesar, don't be surprised when they come back as Romans.\" For Baucham, the solution is clear: parents must take ownership of their children's education, faith formation, and moral development. That doesn't mean they never partner with others. It does mean they never abdicate. The responsibility belongs to them first.",
      "From Aristotle to Tocqueville, from Peterson to Baucham, the message is consistent: the family is the first and most sacred institution of human society. Parents, not governments or schools, are entrusted with the lives of their children. This truth has practical consequences. It means parents must step into their role with confidence and conviction. It means communities must respect the boundaries between public authority and private family life. And it means that when parents are pressured to step aside, they must have the courage to stand firm. At Honor Bound FIT, we reinforce responsibility, discipline, and ownership — just as no one else can lift the weight for you, no one else can raise your children for you. Children belong to their parents. It has always been true. It will always be true.",
    ],
  },
  {
    number: 6,
    title: "Good Friends Have Hard Conversations",
    slug: "good-friends",
    excerpt:
      "Good friends don't let you drift. Good friends don't let you lie to yourself. Good friends have hard conversations.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2025/11/Hard-Conversations.avif",
    body: [
      "There's a certain kind of friendship that never disagrees, never challenges, never risks discomfort. Everything is smooth. Everything is \"fine.\" Nothing difficult is ever said. And those friendships never last. They collapse under the weight of everything that was left unsaid — because avoiding hard conversations is nothing more than delaying the truth. Whether you're leading Marines, raising a family, showing up for a brother, or standing inside a gym community that demands excellence, one principle holds steady: Good friends don't let you drift. Good friends don't let you lie to yourself. Good friends have hard conversations.",
      "Jocko's philosophy is simple: if something is wrong and you're not addressing it, you are part of the problem. Extreme Ownership isn't just about missions, teams, and leadership — it's about relationships. Hard conversations are preventative maintenance. They are the leadership equivalent of checking your gear, maintaining your weapon, or tightening up your form on a heavy lift. You don't skip those things out of politeness; you do them because lives, limbs, and futures depend on it. To Jocko, accountability is not aggression — it's an act of service. Good friends tell you the truth before the world punishes you with it.",
      "Jordan Peterson describes resentment as one of the most dangerous human emotions. It's what fills the vacuum when truth is left unsaid. When we avoid difficult conversations, we don't create peace — we create tension disguised as peace. As Peterson says: \"If you avoid responsibility, you harshen your life.\" Holding in what must be said eventually twists into bitterness, passive-aggressive behavior, or silent distance. Friendships break. Marriages erode. Teams fracture. Families fall into cycles of pain that last decades. Peterson's insight is sharp: when you refuse to speak the truth, you are not avoiding conflict — you are merely postponing it, guaranteeing that the eventual conflict will be far worse.",
      "Admiral James Stockdale — Medal of Honor recipient, POW, philosopher — had a principle that applies directly to this core value: confront the brutal facts without losing faith in the long-term outcome. That's the Stockdale Paradox. His survival depended on engaging with reality exactly as it was, not as he wished it to be. A real friend doesn't let you build a fantasy that everything is fine when it's not. A real friend won't let you drift into self-deception or bad habits. Hard conversations are the civilian version of battlefield courage — they're smaller, quieter, but they come from the same place: the willingness to face what is painful for the sake of what is right.",
      "In Greenlights, Matthew McConaughey talks often about life's \"red lights\" that turn green only after you confront what you've been avoiding. Good friends perform that function for each other. They are mirrors. They reflect what you can't see, won't see, or don't want to see. Sometimes the green light you need is a friend who cares enough to speak the truth.",
      "Dallas Willard, the philosopher-theologian, brings the warmest — and arguably the strongest — layer to this value. His teaching rests on the idea that truth without love is brutality, and love without truth is sentimentality. Hard conversations belong right in the middle. Willard argued that real love tells the truth because it is invested in the other person's growth. Conversely, \"being nice\" while silently watching a friend self-destruct is not love — it's abandonment dressed in politeness. Jocko gives us discipline and responsibility. Peterson gives us psychological clarity. Stockdale gives us moral courage. McConaughey gives us self-reflection. Willard gives us grace and compassion. Those five voices together form a complete picture of why hard conversations matter — and how to do them well.",
      "The people who challenge you care the most. The people who stay silent care the least. Hard conversations are not about winning. They are not about ego. They are not about proving a point. They are about calling each other to the highest version of ourselves. Iron sharpens iron. But only if the blades make contact. At Honor Bound FIT, we don't avoid the sparks. We embrace them. Because good friends have hard conversations — and that's exactly why they stay good friends.",
    ],
  },
  {
    number: 7,
    title: "Regardless of Environment, Circumstances, and Opposition: Individuals Are Responsible for Their Own Attitudes, Behavior, and Outcomes.",
    slug: "regardless-of-environment",
    excerpt:
      "Circumstances may explain difficulty, but they never absolve responsibility. Environment influences the terrain — not the obligation to move.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2025/12/Trial-of-Sisyphus.avif",
    body: [
      "Modern culture is quick to explain behavior as a product of circumstance. Environment, upbringing, injustice, trauma, and opposition are often treated not only as factors, but as final verdicts for outcomes. While these forces undeniably shape difficulty, they do not absolve responsibility.",
      "Epictetus, born into slavery around the time of Jesus's death, articulated this truth with precision. He taught that while we do not control events, we always control our judgments, choices, and actions. To surrender responsibility for those things is to surrender the only leverage we possess. External forces may limit options, but they never relieve us of the obligation to govern ourselves. The moment we start outsourcing our responsibility, progress becomes impossible.",
      "Admiral James Stockdale proved this principle under conditions few would survive. As a prisoner of war in North Vietnam, he was stripped of freedom, comfort, and certainty. Yet he retained moral agency. Stockdale rejected false optimism and instead committed to discipline, dignity, and leadership — choosing conduct over circumstance. His captivity demonstrated a hard truth: if responsibility can survive years of torture and isolation, it can survive inconvenience, adversity, and opposition in ordinary life.",
      "Frederick Douglass confronted a different, but equally unforgiving, reality. Like Epictetus, also born into slavery, Douglass refused to internalize the idea that injustice defined his destiny. Through education, self-command, and relentless effort, he asserted agency where society denied it. Douglass did not deny the brutality of his circumstances; he rejected the claim that they excused passivity. His life stands as a rebuke to the notion that environment alone determines outcome.",
      "A subtle but corrosive shift occurs when hardship is treated not as an obstacle to be confronted, but as a veto on responsibility. When people claim that forces such as racism, patriarchy, or systemic bias make progress impossible, they do more than describe injustice — they quietly discredit those who have overcome those same barriers. Discipline is reframed as a fluke. Persistence is dismissed as an anomaly. Earned success is treated as an accident rather than the product of effort, character, and sacrifice. This does not deny the existence of injustice; it denies the legitimacy of human resilience.",
      "Jocko Willink translates this moral truth into modern language through the principle of Extreme Ownership. Progress begins only when responsibility is accepted fully and without condition. Blame — whether assigned to systems, people, or circumstances — halts improvement. Ownership, even when it feels unfair, creates leverage. Angela Duckworth's research on grit reinforces this reality with empirical clarity. Long-term outcomes are not the product of talent or favorable conditions, but of sustained effort over time. Motivation fluctuates. Circumstances change. Responsibility endures.",
      "Taken together, Epictetus, Stockdale, Douglass, Jocko, and Duckworth converge on a single, demanding truth: circumstances may explain difficulty, but they never absolve responsibility. Environment influences the terrain, not the obligation to move. Opposition tests resolve — it does not negate it. Responsibility is not a burden imposed from the outside; it is the foundation of dignity, progress, and freedom. Those who govern themselves first remain capable, regardless of the world around them.",
    ],
  },
  {
    number: 8,
    title: "Surround Yourself With Good People Who Hold You Accountable to Your Values, Goals, and Commitments.",
    slug: "surround-yourself",
    excerpt:
      "Your environment will always win if you let it. Standards do not collapse overnight — they decay through permission.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2025/06/Murphiversary-25.jpg",
    body: [
      "\"Your input determines your outlook. Your outlook determines your output, and your output determines your future.\" – Zig Ziglar",
      "If the people in your circle tolerate excuses, you will eventually make them. If they accept half-effort, you will deliver half-effort. If they look the other way when commitments are missed, integrity will erode quietly, then all at once. This is not theory; this is observable reality in every high-performing organization that has ever failed. Standards do not collapse overnight; they decay over time through permission. One exception becomes a precedent, one compromise becomes policy, one leader looks away, and suddenly the standard has become \"that's how we're SUPPOSED to do it.\"",
      "There's another layer to this that's often ignored: you must surround yourself with people who are playing the same game you are. Human beings naturally compare, compete, and calibrate themselves against those around them. That competition is not inherently bad — it is inevitable. The danger is measuring yourself against people who are chasing different outcomes, operating under different rules, or prioritizing comfort while you're pursuing excellence. If your goal is discipline, but your peers optimize for convenience, their \"wins\" will quietly pressure you to lower your bar. The solution is alignment. Surround yourself with people who want the same things you want: integrity over image, standards over shortcuts, durability over applause. In that environment, competition becomes constructive. Iron sharpens iron.",
      "Recently, America has become aware of a troubling shift among its military leadership in how advancement and authority are earned. Accountability has too often been replaced by career preservation, and progressing through the ranks has become less about competence, results, or character and more about adherence to approved ideas. Those who repeat the correct talking points are protected and promoted, while those who insist on inconvenient standards are sidelined or punished. When loyalty to an ideology outweighs loyalty to the mission, standards do not merely erode — they are deliberately sacrificed. Senior enlisted leaders bear a profound obligation. Apart from accomplishing the immediate mission of the day and maintaining the morale and readiness of their subordinates, what greater responsibility do our senior enlisted have than to uphold standards and preserve military culture? When standards fail, missions fail, and people pay the price.",
      "Good people prevent failure long before it reaches crisis. They speak up early. They enforce standards consistently. They are willing to risk comfort, popularity, and even position to protect what actually matters. They do not confuse compassion with permissiveness nor leadership with consensus. They hold the line against the comfortable decay of negligence and compromise. If you claim discipline but surround yourself with people who celebrate comfort, you are lying to yourself. If you claim commitment but keep company with those who rationalize quitting, your values are rhetorical at best. Your environment will always win if you let it.",
      "At Honor Bound FIT, we believe community is not about comfort — it's about alignment. The strongest teams, families, and communities are built on shared values and the courage to enforce them. If you want to become more disciplined, more capable, and more reliable, start by ensuring the people around you expect nothing less.",
    ],
  },
  {
    number: 9,
    title: "Relentlessly Pursue the Things You Suck At Until Today's Challenges Are Tomorrow's Warm-ups.",
    slug: "relentlessly-pursue",
    excerpt:
      "Comfort is a liar. Progress lives on the other side of the things you currently struggle to do.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2026/03/relentless-pursuit-scaled.avif",
    body: [
      "Everyone enjoys doing the things they're good at. It feels good to move weight you know you can handle. It feels good to run distances you've already conquered. It feels good to operate inside the boundaries of competence. But comfort is a liar. \"Comfort is an illusion; a false security bred from familiar things and familiar ways. It narrows the mind, weakens the body, and robs the soul of spirit and determination.\" – Alex Lowe. Comfort tells you that repeating what you already do well is progress. None of that is true. Progress lives on the other side of the things you currently struggle to do.",
      "The movements you avoid are not accidents. They are signals. If you hate front rack mobility, that's a sign. If your pull-ups stall at three reps, that's a sign. If rucking uphill crushes you, that's a sign. Weakness is not something to hide from. Weakness is the map showing you exactly where to go next. The problem is that most people spend their training time polishing their strengths instead of developing their deficiencies. They squat more because they're already good at squatting. They skip mobility because it's uncomfortable and slow. That approach creates impressive strengths resting on top of unresolved limitations.",
      "To improve at the things you suck at requires a particular kind of humility. You have to own your limitations in order to conquer new growth. You must be willing to look awkward, move slower than others, use lighter weight, and fail repeatedly. That's uncomfortable for people who attach their identity to performance. But the individuals who improve the fastest are the ones willing to temporarily look the worst. Skill development requires time under tension with your own ego.",
      "Nobody wakes up excited to practice what they're bad at. Motivation usually follows success, not the other way around. The early stages of improvement are frustrating and slow. Your progress feels invisible. You question whether the effort is worth it. This is where discipline takes over. Discipline says: do the work anyway. Five extra minutes of mobility. Three extra sets of skill practice. One more attempt at the movement that exposed your weakness. Stack those days long enough, and the impossible begins to feel manageable.",
      "There is a quiet satisfaction that comes from revisiting something that used to defeat you. The weight that once pinned you now moves smoothly. The distance that once crushed you becomes a routine run. The mobility restriction that once limited you becomes part of your warm-up. The obstacle did not disappear. You simply grew beyond it. That transformation is the real purpose of training. Not just stronger muscles, but a stronger character that refuses to remain limited by yesterday's shortcomings.",
      "At Honor Bound FIT, we don't hide from our weaknesses. We hunt them. If something exposes a limitation, we take note. If a movement frustrates us, we practice it. If a workout humbles us, we revisit it. Not occasionally. Relentlessly. The goal isn't to look good during training. The goal is to become harder to break.",
    ],
  },
  {
    number: 10,
    title: "Compare Yourself to Who You Were Yesterday, Not to Who Someone Else Is Today.",
    slug: "compare-yourself",
    excerpt:
      "The moment you walk into the gym and start looking around, you've already lost. The only competition that counts is the version of yourself from yesterday.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2026/03/Comparison.avif",
    body: [
      "The moment you walk into the gym and start looking around, you've already lost. I know that feeling. You rack up a weight that feels heavy to you, and three feet away some guy is warming up with it. You're grinding through a set and the woman next to you finishes her fifth and barely looks winded. You came in with intention and within sixty seconds the comparison machine in your head is already running, already doing the math, already telling you that you're behind, that you don't belong here, that maybe this isn't for you. I'm not going to tell you that feeling is wrong. It's human. It's also completely useless.",
      "Here's the thing about comparison — it doesn't care which direction it runs. Sometimes you walk in and you're ahead of the people around you, and that feels good for about a minute before it makes you lazy or arrogant. Sometimes you're behind, and it hollows you out. Either way, you're not training anymore. You're performing. You're measuring yourself against a standard that has nothing to do with you, your history, your body, your reasons for being there. You've handed your motivation over to a stranger who doesn't know your name and doesn't care about your progress. That's the trap. And most people never see it for what it is.",
      "Jordan Peterson puts it plainly: compare yourself to who you were yesterday, not to who someone else is today. That's not a motivational poster. That's a precision instrument. What it's saying is that you are a specific person with a specific history — injuries, setbacks, starting points, and reasons that belong entirely to you. The guy lifting twice your weight has been doing this for eight years. The woman who runs a six-minute mile has been running since high school. Their metrics tell you nothing about where you should be. Nothing. Their progress is theirs. Your progress is yours. The comparison is literally meaningless, and treating it like a benchmark is how people quit.",
      "Viktor Frankl survived things most of us can't imagine, and one of the things he understood was that meaning comes from the inside out, not the outside in. The person who walks into the gym because they want to be alive and healthy for their kids, because they want to carry their own groceries at seventy-five, because they made a promise to themselves — that person has something to work with. The person chasing someone else's standard is building on sand. The second they fall behind, the whole thing collapses.",
      "I spent years in the Marine Corps where physical performance was measurable, tracked, and compared constantly. That environment produces a certain kind of motivation, but it also produces a certain kind of fragility. The ones who lasted — the ones who stayed fit and healthy long after they left service — they weren't the ones who needed to be best. They were the ones who showed up. Consistently. For their own reasons. Measured against themselves.",
      "In practice, this means keeping your own records. Write down your lifts. Track your times. Note when you added five pounds or did one more rep or shaved thirty seconds off your run. Those numbers are yours. They tell a story that belongs to you. It means showing up when you don't feel like it and defining success by the showing up, not by what you performed that day. It means staying in your lane. That's not weakness. That's focus. The person next to you isn't your competition. They never were. You walked in the door. That already separates you from most people. What you do with it is between you and the version of yourself from yesterday. Win that fight. That's the only one that counts.",
    ],
  },
  {
    number: 11,
    title: "Respect Is Given Before It Is Earned",
    slug: "respect-is-given-before-it-is-earned",
    excerpt:
      "Respect is not a reward for performance. It is a posture — the position you take before you know anything about the person standing next to you.",
    imageUrl: "https://honorboundfit.com/wp-content/uploads/2026/04/respect-scaled.avif",
    body: [
      "Most people think respect is a transaction. You show up, you perform, you earn it. That's how it works in most places: you pay your dues, you prove yourself, and eventually the veterans in the room acknowledge your existence. That's not how we do it here. At Honor Bound FIT, respect is not a reward for performance. It is a posture. It's the position you take before you know anything about the person standing next to you; before they've lifted a single weight or proven a single thing. You give it on day one, unconditionally, because they walked through the door. That's enough. This isn't naive. It's a standard. Like all real standards, it demands more of you, not less.",
      "Aristotle argued that the polis — the community — is not a collection of strangers tolerating each other. It is a shared project requiring trust as its raw material. Trust doesn't grow from performance reviews. It grows from the basic assumption that the people around you are worthy of dignity until they prove otherwise. In a gym, this matters more than people realize. You are training alongside someone in a vulnerable state — pushing past what's comfortable, failing reps in public, sweating through things that don't come easy. If the environment they walk into requires them to earn your basic regard first, to perform their way into your respect, you've built a culture of auditions. And people in audition mode don't train freely. They train cautiously. They protect their ego instead of attacking their weakness. You've made the gym smaller.",
      "Jocko Willink teaches that good leadership doesn't wait for performance before it invests in people. You don't withhold trust from your team until they've proven themselves mission after mission. You extend trust, you explain the standard, and you hold them to it. That sequence — extend first, then hold accountable — is the only way to build a team capable of actual performance under pressure. Withholding respect until it's earned assumes the worst about people. It creates a defensive culture. And a defensive culture will never outperform an invested one. Respect given freely isn't softness. It's a declaration: I believe you're capable of something. Prove me right. That is a higher standard, not a lower one.",
      "This value shows up in small ways that compound. You learn someone's name. You acknowledge a new member instead of waiting for them to prove they belong. You don't compare or rank. The person grinding through their first workout deserves the same regard as the athlete who's been here for years. When someone fails a lift, you don't look away. You acknowledge it. Failure respected is failure survived. The gym is a rehearsal for life. The respect you practice here — automatic, unconditional, unearned — is the respect you carry into your home, your workplace, your neighborhood. It is a discipline, and like all disciplines, it requires repetition before it becomes instinct.",
      "Respect given before it's earned doesn't mean respect given regardless of conduct. The standard is clear: you receive it because you walked in. You keep it through how you carry yourself. If you violate it — if you undermine someone else's dignity, if you bring arrogance or contempt into our space — you don't lose our respect slowly. You lose it immediately. A culture that gives respect unconditionally also defends it ferociously. At Honor Bound FIT, we believe a tribe that can look a stranger in the eye on day one and say \"you belong here,\" is a tribe capable of doing hard things together. Respect isn't the reward at the end of the road. It is the road. Walk it from the beginning.",
    ],
  },
  {
    number: 12,
    title: "Be Useful.",
    slug: "be-useful",
    excerpt:
      "Usefulness is not a personality trait. It is a daily decision — a commitment to showing up with more than you consume.",
    body: [
      "To be useful is to orient your life toward something outside yourself. It is the opposite of entitlement, the antidote to self-absorption, and the only reliable source of meaning that survives contact with reality.",
      "Jordan Peterson distills this to its sharpest form: clean your room. Not because the room matters, but because the act of putting order into your immediate environment is the beginning of putting order into your life. From there you can put order into your community. From there, outward. The useful man starts small and compounds.",
      "In a training environment, usefulness looks like stacking weights for others, sharing space generously, showing up when the session is hard and the weather is worse. It means not treating the gym as a theater for your own performance but as a shared project that depends on everyone pulling their weight — literally.",
      "Be useful. Every day. Without waiting to be asked.",
    ],
  },
  {
    number: 13,
    title: "Treat Others Not as You Wish to Be Treated, But How They Wish to Be Treated.",
    slug: "treat-others-how-they-wish",
    excerpt:
      "The Golden Rule is a starting point, not a ceiling. Real service requires paying attention to the person in front of you, not the person you imagine yourself to be.",
    body: [
      "The Golden Rule — treat others as you wish to be treated — is one of the most broadly shared moral intuitions in human history. It appears in nearly every major religious and philosophical tradition. And it is a good starting point. But it has a flaw: it centers you.",
      "If you treat others as you wish to be treated, you are projecting your own preferences onto them. You are assuming what they need based on what you would want. Sometimes that works. Often it doesn't. The person who likes direct, blunt feedback gives direct, blunt feedback — and wounds someone who needed gentleness first. The person who hates being fussed over ignores someone who needed to feel seen.",
      "The upgrade is simple and demanding: pay attention. Ask. Listen. Adjust. Treat people how they wish to be treated, which means you must first learn what that is. This requires setting aside your own preferences long enough to actually perceive the person in front of you. That is not a small thing.",
      "At Honor Bound FIT, this value is lived in coaching. A coach who applies the same approach to every athlete is not coaching — they are performing. Real coaching begins with observation and ends with adaptation. The same rep scheme, the same cue, the same tone does not work for everyone. What works is the coach who sees who they're actually working with.",
    ],
  },
  {
    number: 14,
    title: "Treat All People Like Individuals, Not Obstacles or Objectives.",
    slug: "treat-people-as-individuals",
    excerpt:
      "Every person who walks through the door is somebody. Not a number, not a subscription, not a demographic.",
    body: [
      "There are two ways to fail the people around you. The first is to treat them as obstacles — inconveniences to be managed, problems to be routed around, friction in the system. The second is to treat them as objectives — targets to be converted, metrics to be moved, opportunities to be captured. Both reduce a human being to a function. Both are wrong.",
      "The problem with comparing yourself to others is that the sample set is arbitrary and the data is misleading. You are comparing your insides to their outsides. You are comparing your full complexity — your history, your struggles, your context — to a surface image. You will almost always lose this comparison, not because you are behind, but because the comparison is structurally rigged. There is always someone further along. There is always someone with more.",
      "At Honor Bound FIT, everyone who walks through that door is somebody. Not a number, not a subscription, not a demographic. They have a reason they came. They have something they're trying to build or repair or maintain. They are trusting us with their time, their bodies, and in many cases their self-image. We take that seriously. We see them. And we expect everyone in this community to extend that same regard to everyone else here — because a gym that treats people as individuals is something entirely different from a gym that treats people as members.",
    ],
  },
]

export function getCoreValueBySlug(slug: string): CoreValue | undefined {
  return CORE_VALUES.find((v) => v.slug === slug)
}
