import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy | Honor Bound FIT',
  description:
    'Privacy Policy for Honor Bound FIT LLC — how we collect, use, and protect your personal information.',
}

export default function PrivacyPage() {
  return (
    <main className="bg-black text-white min-h-screen font-montserrat pt-16">

      {/* DRAFT Banner */}
      <div className="bg-amber-400 text-black text-center py-3 px-4 font-bold text-sm tracking-widest uppercase">
        ⚠ DRAFT — NOT YET IN EFFECT — FOR REVIEW PURPOSES ONLY ⚠
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12 leading-relaxed">

        {/* Title */}
        <h1 className="text-3xl font-black uppercase tracking-widest text-white mb-2 font-montserrat">
          Privacy Policy
        </h1>
        <p className="text-xs text-zinc-500 mb-2">
          <strong className="text-zinc-400">Effective Date:</strong> TBD &nbsp;·&nbsp;
          <strong className="text-zinc-400">Last Updated:</strong> DRAFT
        </p>
        <p className="text-xs text-zinc-500 mb-10">
          Honor Bound FIT LLC &nbsp;·&nbsp; 45 Centreport Parkway Suite 137, Fredericksburg, VA 22406
          <br />
          <a href="mailto:rich@honorboundfit.com" className="text-amber-400 underline">
            rich@honorboundfit.com
          </a>
          <br />
          <span className="text-amber-400 font-semibold">DRAFT — Review by a qualified Virginia attorney recommended before use.</span>
        </p>

        <p className="text-zinc-300 mb-10">
          Honor Bound FIT LLC ("HBFIT," "we," "us," or "our") is committed to protecting the privacy of our
          members, prospective members, and website visitors. This Privacy Policy explains what personal
          information we collect, how we use it, with whom we share it, and the rights you have with respect to
          your information. By enrolling in a membership, attending HBFIT activities, or using our website, you
          acknowledge and agree to the practices described in this Policy.
        </p>

        {/* ─── SECTION 1: DATA COLLECTED ─── */}
        <section id="data-collected" className="mb-12">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            1. Information We Collect
          </h2>
          <p className="text-zinc-300 mb-4">
            We collect information you provide directly to us, information generated by your participation in
            HBFIT activities, and limited technical information from your use of our website.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            1.1 Identity &amp; Contact Information
          </h3>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Full legal name',
              'Date of birth',
              'Mailing address and email address',
              'Phone number(s)',
              'Profile photo (if voluntarily provided)',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            1.2 Emergency Contact Information
          </h3>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Emergency contact name, relationship, and phone number',
              'Any additional emergency contact details you choose to provide',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            1.3 Health &amp; Medical Information
          </h3>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Health history and self-reported medical conditions relevant to safe participation',
              'Current medications relevant to exercise safety',
              'Known allergies or physical limitations',
              'Pre-participation health questionnaire responses',
              'Physician clearance documentation (if applicable)',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            1.4 Payment Information
          </h3>
          <p className="text-zinc-300 mb-4">
            Billing and payment processing is handled through Stripe, Inc. HBFIT collects your name and billing
            address for invoicing purposes. <strong className="text-white">HBFIT does not collect, store, or have
            access to your full credit card or bank account numbers.</strong> See Section 4 for more information
            on our Stripe integration.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            1.5 Attendance &amp; Participation Records
          </h3>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Session attendance history and check-in records',
              'Class or program enrollment records',
              'Participation in events, competitions, or special programming',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            1.6 Fitness Progress &amp; Coaching Notes
          </h3>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Performance benchmarks, test results, and tracked metrics (e.g., lifts, times, body weight if voluntarily shared)',
              'Coaching notes and programming adjustments',
              'Goal-setting records and progress assessments',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            1.7 Website Analytics
          </h3>
          <ul className="list-none space-y-2 mb-4">
            {[
              'IP address, browser type, device type, and operating system',
              'Pages visited, time spent on pages, referral URLs',
              'Cookies and similar tracking technologies (see our Cookie notice below)',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="text-zinc-300 mb-4">
            Website analytics data is used in aggregate to improve our website and is not linked to individual
            member profiles unless you are logged into a member account.
          </p>
        </section>

        {/* ─── SECTION 2: HOW WE USE DATA ─── */}
        <section id="how-used" className="mb-12 bg-zinc-950 rounded-lg p-6 border border-white/10">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            2. How We Use Your Information
          </h2>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            2.1 Membership Management
          </h3>
          <p className="text-zinc-300 mb-4">
            We use your identity, contact, and attendance information to create and manage your HBFIT membership
            account, process enrollment, track participation, and communicate membership status updates including
            renewals, billing notices, schedule changes, and policy updates.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            2.2 Billing &amp; Payment Processing
          </h3>
          <p className="text-zinc-300 mb-4">
            Your billing information is used to process 4-week membership cycle payments, issue receipts, manage
            failed payment follow-up, and process any applicable refunds. All payment transactions are processed
            securely by Stripe (see Section 4).
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            2.3 Member Communications
          </h3>
          <p className="text-zinc-300 mb-4">
            We use your contact information to send:
          </p>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Transactional emails: membership confirmations, billing receipts, schedule updates, policy changes',
              'Operational communications: class changes, facility closures, safety notices',
              'Coaching and programming updates relevant to your participation',
              'Marketing and promotional content — only with your explicit consent, and only to members who have opted in',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="text-zinc-300 mb-4">
            <strong className="text-white">We do not send marketing communications without your consent.</strong>{' '}
            You may withdraw consent for marketing communications at any time (see Section 6).
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            2.4 Safety &amp; Emergency Purposes
          </h3>
          <p className="text-zinc-300 mb-4">
            Health and emergency contact information is used to ensure your safety during training and to
            facilitate emergency response if needed. Coaches are informed of relevant health conditions or
            limitations to provide safe, appropriate programming and supervision.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            2.5 Coaching &amp; Program Development
          </h3>
          <p className="text-zinc-300 mb-4">
            Fitness progress data and coaching notes are used to personalize your training experience, track
            your development over time, and improve HBFIT's coaching programs and overall service quality.
          </p>
        </section>

        {/* ─── SECTION 3: STRIPE ─── */}
        <section id="stripe" className="mb-12">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            3. Payment Processing &amp; Stripe
          </h2>

          <div className="bg-zinc-900 border border-white/10 rounded-lg p-5 mb-6">
            <p className="text-zinc-200 text-sm leading-7">
              <strong className="text-white text-base">HBFIT does not store your payment card numbers.</strong>
              {' '}Full card numbers, CVV codes, and bank account details are never transmitted to or stored on
              HBFIT's systems. All payment processing is handled exclusively by{' '}
              <strong className="text-white">Stripe, Inc.</strong>, a leading payment infrastructure provider
              certified at{' '}
              <strong className="text-white">PCI DSS Level 1</strong> — the highest level of payment card
              industry security certification.
            </p>
          </div>

          <p className="text-zinc-300 mb-4">
            When you provide payment information during enrollment, that information is collected and encrypted
            directly by Stripe. HBFIT receives only a tokenized representation of your payment method, which
            allows us to initiate recurring billing charges without accessing your actual card data.
          </p>
          <p className="text-zinc-300 mb-4">
            Stripe's use of your payment data is governed by their own Privacy Policy, which you can review at{' '}
            <a
              href="https://stripe.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-amber-400 underline"
            >
              stripe.com/privacy
            </a>
            .
          </p>
          <p className="text-zinc-300 mb-4">
            HBFIT retains billing records (transaction dates, amounts, membership tier) as required for
            accounting, tax, and dispute resolution purposes.
          </p>
        </section>

        {/* ─── SECTION 4: DATA SHARING ─── */}
        <section id="data-sharing" className="mb-12 bg-zinc-950 rounded-lg p-6 border border-white/10">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            4. How We Share Your Information
          </h2>

          <div className="bg-zinc-900 border border-amber-400/30 rounded-lg p-4 mb-6">
            <p className="text-amber-400 font-bold text-sm uppercase tracking-wide mb-1">Our Core Commitment</p>
            <p className="text-zinc-200 text-sm">
              <strong>HBFIT does not sell, rent, or trade your personal information to any third party for
              commercial or marketing purposes. Ever.</strong>
            </p>
          </div>

          <p className="text-zinc-300 mb-4">
            We share your information only in the following limited circumstances:
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            4.1 Service Providers
          </h3>
          <p className="text-zinc-300 mb-4">
            We engage a limited number of trusted service providers who assist us in operating our business.
            These providers are permitted to access personal information only to perform their services for HBFIT
            and are contractually prohibited from using it for any other purpose. Current categories of service
            providers include:
          </p>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Payment processing: Stripe, Inc.',
              'Email communications: email service provider used for member communications',
              'Website hosting and infrastructure: web hosting providers',
              'Member management software: any platform used to manage scheduling and memberships',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            4.2 Legal Requirements
          </h3>
          <p className="text-zinc-300 mb-4">
            We may disclose your information if required to do so by law, regulation, court order, or lawful
            request of governmental authorities, or when we believe disclosure is necessary to protect the rights,
            property, or safety of HBFIT, our members, or the public.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            4.3 Business Transfers
          </h3>
          <p className="text-zinc-300 mb-4">
            In the event of a merger, acquisition, or sale of all or substantially all of HBFIT's assets, member
            information may be transferred as part of that transaction. You will be notified via email and/or
            prominent notice on our website prior to any such transfer and any material change to how your
            information is used.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            4.4 With Your Consent
          </h3>
          <p className="text-zinc-300">
            We may share information with third parties when you have given us explicit consent to do so (for
            example, if you consent to being featured in HBFIT marketing materials or social media).
          </p>
        </section>

        {/* ─── SECTION 5: HEALTH DATA ─── */}
        <section id="health-data" className="mb-12">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            5. Health &amp; Medical Information
          </h2>

          <div className="bg-zinc-900 border border-white/10 rounded-lg p-5 mb-6">
            <p className="text-zinc-200 text-sm leading-7">
              HBFIT treats health and medical information with the{' '}
              <strong className="text-white">highest level of confidentiality</strong>. This information is
              collected solely to ensure member safety during training and to allow our coaching staff to provide
              appropriate programming and supervision.
            </p>
          </div>

          <ul className="list-none space-y-3 mb-4">
            {[
              "Health information is accessible only to HBFIT's owner and coaching staff who have a direct training relationship with you.",
              'Health information is not shared with other members.',
              'Health information is never sold, rented, or disclosed to third parties for commercial purposes.',
              'Health information may be shared with emergency responders in a life-threatening emergency.',
              'Health information may be disclosed if required by law or a valid court order.',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 font-bold shrink-0 mt-0.5">▸</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* ─── SECTION 6: MEMBER RIGHTS ─── */}
        <section id="member-rights" className="mb-12 bg-zinc-950 rounded-lg p-6 border border-white/10">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            6. Your Rights as a Member
          </h2>

          <p className="text-zinc-300 mb-4">
            You have the following rights with respect to your personal information held by HBFIT:
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            6.1 Right of Access
          </h3>
          <p className="text-zinc-300 mb-4">
            You may request a copy of the personal information HBFIT holds about you. We will provide this
            information within a reasonable timeframe.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            6.2 Right of Correction
          </h3>
          <p className="text-zinc-300 mb-4">
            You may request that we correct any inaccurate or incomplete personal information. To update your
            contact information, health records, or emergency contacts, contact us at{' '}
            <a href="mailto:rich@honorboundfit.com" className="text-amber-400 underline">
              rich@honorboundfit.com
            </a>
            .
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            6.3 Right of Deletion
          </h3>
          <p className="text-zinc-300 mb-4">
            You may request deletion of your personal information. We will honor deletion requests subject to
            our obligation to retain certain records as required by law (e.g., tax and billing records) or as
            necessary to resolve disputes or enforce our agreements. After your membership ends, we will retain
            your records for a reasonable period before deletion.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            6.4 Opt-Out of Marketing Communications
          </h3>
          <p className="text-zinc-300 mb-4">
            You may opt out of marketing emails at any time by clicking the "unsubscribe" link in any marketing
            email, or by contacting us at{' '}
            <a href="mailto:rich@honorboundfit.com" className="text-amber-400 underline">
              rich@honorboundfit.com
            </a>
            . Note that opting out of marketing communications does not affect transactional or operational
            communications related to your active membership.
          </p>

          <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 mt-6 mb-2">
            6.5 Photo &amp; Media Consent Revocation
          </h3>
          <p className="text-zinc-300 mb-4">
            If you have previously consented to HBFIT using your image, name, or likeness in marketing
            materials, social media, or other promotional content, you may revoke that consent at any time by
            contacting us at{' '}
            <a href="mailto:rich@honorboundfit.com" className="text-amber-400 underline">
              rich@honorboundfit.com
            </a>
            . Revocation will be honored for future use; it does not require us to remove content already
            published and in circulation.
          </p>
        </section>

        {/* ─── SECTION 7: VCDPA ─── */}
        <section id="vcdpa" className="mb-12">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            7. Virginia Consumer Data Protection Act (VCDPA)
          </h2>

          <p className="text-zinc-300 mb-4">
            HBFIT acknowledges the Virginia Consumer Data Protection Act (Va. Code § 59.1-575 et seq.) and is
            committed to honoring the rights it provides to Virginia residents. Virginia residents have the right
            to:
          </p>
          <ul className="list-none space-y-2 mb-4">
            {[
              'Know whether HBFIT is processing personal data about them',
              'Access personal data HBFIT holds about them',
              'Correct inaccuracies in their personal data',
              'Delete personal data provided by or obtained about them',
              'Obtain a copy of their personal data in a portable and readily usable format',
              'Opt out of targeted advertising, sale of personal data, or profiling (note: HBFIT does not sell personal data or engage in targeted advertising or profiling)',
            ].map((item, i) => (
              <li key={i} className="flex gap-3 text-zinc-300">
                <span className="text-amber-400 shrink-0 mt-0.5">→</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="text-zinc-300 mb-4">
            To exercise any VCDPA right, contact HBFIT at{' '}
            <a href="mailto:rich@honorboundfit.com" className="text-amber-400 underline">
              rich@honorboundfit.com
            </a>
            . We will respond to verified requests within the timeframes required by applicable law.
          </p>
          <p className="text-xs text-zinc-500 italic">
            Note: Whether HBFIT meets the VCDPA's applicability thresholds (100,000 consumers / 25,000 with 50% revenue from data sales) should be confirmed with legal counsel. This section is included as a best-practice commitment regardless of strict threshold applicability.
          </p>
        </section>

        {/* ─── SECTION 8: DATA SECURITY & RETENTION ─── */}
        <section id="security" className="mb-12 bg-zinc-950 rounded-lg p-6 border border-white/10">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            8. Data Security &amp; Retention
          </h2>
          <p className="text-zinc-300 mb-4">
            HBFIT implements reasonable administrative, technical, and physical safeguards to protect your
            personal information from unauthorized access, use, or disclosure. However, no security system is
            impenetrable and we cannot guarantee absolute security.
          </p>
          <p className="text-zinc-300 mb-4">
            We retain member information for as long as your membership is active and for a reasonable period
            thereafter as necessary to comply with legal obligations, resolve disputes, and enforce our
            agreements. When data is no longer needed, we take reasonable steps to securely delete or
            de-identify it.
          </p>
        </section>

        {/* ─── SECTION 9: CONTACT ─── */}
        <section id="contact" className="mb-12">
          <h2 className="text-xl font-black uppercase tracking-widest text-white mb-4 border-b border-white/10 pb-2 font-montserrat">
            9. Contact Us
          </h2>
          <p className="text-zinc-300 mb-4">
            If you have questions, concerns, or requests regarding this Privacy Policy or your personal
            information, please contact us:
          </p>
          <div className="bg-zinc-900 border border-white/10 rounded-lg p-5">
            <p className="text-white font-bold mb-1">Honor Bound FIT LLC</p>
            <p className="text-zinc-300 text-sm">45 Centreport Parkway Suite 137</p>
            <p className="text-zinc-300 text-sm mb-3">Fredericksburg, VA 22406</p>
            <p className="text-zinc-300 text-sm">
              Email:{' '}
              <a href="mailto:rich@honorboundfit.com" className="text-amber-400 underline">
                rich@honorboundfit.com
              </a>
            </p>
          </div>
        </section>

        {/* Draft footer */}
        <div className="bg-amber-400 text-black text-center py-3 px-4 font-bold text-sm tracking-widest uppercase rounded-lg mb-8">
          ⚠ DRAFT — NOT LEGALLY EFFECTIVE — ATTORNEY REVIEW REQUIRED BEFORE USE ⚠
        </div>

        {/* Back to top */}
        <div className="text-center mt-8 pb-8">
          <a
            href="#"
            className="text-xs uppercase tracking-widest text-zinc-500 hover:text-white transition-colors"
          >
            ↑ Back to Top
          </a>
        </div>

      </div>
    </main>
  )
}
